### ISSUE TITLE
marmap: is there a way to find other handles aside from "nw.atlantic" and "hawaii"?

### ISSUE THREAD

**Issue by timmaflanagan** [ericpante/marmap#19]
Hi there! i am looking to use a handle for the "Pacific North west" of the US. Does marmap have any documentation on how to find specific handles like this? 

Is there another way aside from using the tag to choose the location?

This is an example that uses the handle/tag I am referring to: 
# NOT RUN {
# load NW Atlantic data
data(nw.atlantic)

**Comment by besibo** [comment]
`nw.atlantic` and `hawaii` are just 2 toy datasets we decided to include with `marmap` in order to illustrate some of the functions of the package. But since the maximum size of packages is limited by CRAN policies, we can't pack-in too many regions. If you want the list of available datasets pre-packaged with `marmap`, just try `data(package = "marmap")`.

So, if you need to access a specific area, you'll have to use `getNOAA.bathy()` to specify and manually download the data from the ETOPO1 database on NOAA servers, with the added advantage that you'll be able to specify the desired resolution for the area.

Best.

**Comment by timmaflanagan** [comment]
Thank you so much! This is very helpful. Best,

Timma

**Comment by timmaflanagan** [comment]
Hello! I have another question, is it possible to change the colours of image C and D? I am finding, for my plots that I cannot make the distinction clear with regards to where land is/isnt.
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0073051

**Comment by besibo** [comment]
Well, this is not really a `marmap` question... If you take a look at the `3D plotting` section of the `vignette("marmap-DataAnalysis)`, you'll see that these figures are created with `lattice:wireframe()`. So you need to dig into this function help file. Here is also a [good post](https://stackoverflow.com/questions/50230598/r-lattice-wireframe-color) about your specific question.
