### ISSUE TITLE
space.pie(), pie.colors not matching table columns

### ISSUE THREAD

**Issue by ghost** [ericpante/marmap#26]
Hi!  

I'm working with the attached data and the following (truncated) code. 
When I am running said code, the pie proportions are not colored with the color corresponding to the right class, despite the proportions looking right. 
I am not sure what I am doing wrong or if there is an issue with the base code. 

Would there be a way to fix this issue(/is part of my code erroneous), please? 

Cheers

[pie_2000.xlsx](https://github.com/ericpante/marmap/files/8350020/pie_2000.xlsx)

_coul <- brewer.pal(5, "Set2") _
_plot(Azores, type = "n", main = "Ratios of males and females in each quadrant in 2000",
     xlab = "longitude", ylab = "latitude")
polygon(Azores$x, Azores$y, col = "forestgreen")
points(pie_2000[, 9:8], pch=17, col="black", cex=0.5)
space.pies(pie_2000[,9], pie_2000[,8],
           pie.slices = pie_2000[, c(10:14)], pie.colors = pie_2000[, c(15:19)], pie.radius=0.1)
legend("topright", legend=c("Adult Females","Adult Males", "Subadult Females", "Juvenile Females", "Juvenile Male"),
       col=c(coul[1], coul[2], coul[3], coul[4], coul[5]), pch = 20)_

**Comment by besibo** [comment]
Hi !

After investigating, this is clearly a bug in `space.pies()`. The problem comes from the fact that some of your  frequencies are equal to 0. The "empty" pie slices are not drawn(which is correct), but the corresponding colours are not shifted accordingly. So the first non-zero category is associated with the first color of your list, which is obviously wrong.

I'll work on a bugfix for the next minor update of `marmap`, but in the meantime, you can replace the zeros in your proportions by a very small number (i.e. 1e-8)  :

    pie_2000[pie_2000 == 0] <- 0.00000001

This should do the trick!

**Comment by ghost** [comment]
Super, merci beaucoup pour votre aide! Et super package!

**Comment by besibo** [comment]
The bug has been found and squashed! The updated version of marmap (v1.0.7) is now available on github. Install with `remotes::install_github("ericpante/marmap")`.
It will make its way to the CRAN servers with the next round of updates.
